[nordic-wallpaper]
src.git = "https://github.com/linuxdotexe/nordic-wallpapers"
fetch.github = "linuxdotexe/nordic-wallpapers"

[pop-wallpaper]
src.github = "George-Miao/wallpaper"
fetch.github = "George-Miao/wallpaper"

[vscode-linux-x64-stable]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=stable&os=linux-x64'"""
fetch.tarball = "$ver"

[vscode-linux-x64-insider]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=insider&os=linux-x64'"""
fetch.tarball = "$ver"

[vscode-linux-arm64-stable]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=stable&os=linux-arm64'"""
fetch.tarball = "$ver"

[vscode-linux-arm64-insider]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=insider&os=linux-arm64'"""
fetch.tarball = "$ver"

[vscode-darwin-stable]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal'"""
fetch.tarball = "$ver"

[vscode-darwin-insider]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=insider&os=darwin-universal'"""
fetch.tarball = "$ver"
